name = "Pickle"
uuid = "fbb45041-c46e-462f-888f-7c521cafbc2c"
authors = ["chengchingwen <adgjl5645@hotmail.com>"]
version = "0.2.3"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
InternedStrings = "7d512f48-7fb1-5a58-b986-67e6dc259f01"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
DataStructures = "0.17, 0.18"
InternedStrings = "0.7"
Strided = "1.0"
ZipFile = "0.9"
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "PyCall"]
